### ISSUE TITLE
custom date format

### ISSUE THREAD

**Issue by iamaamir** [excaliburhan/vscode-author-generator#10]
i want to change the format of the date so is there anyway to do that?

from the code i could see its hard coded, so anyway to provide the custom format the date ?

https://github.com/excaliburhan/vscode-author-generator/blob/8d97f4501a69bbf2fd07143ece6e2177d42cbeff/generator.js#L88-L90

**Comment by excaliburhan** [comment]
I have published a new version, add `author-generator.dateFormat` config. You can add it in settings.json, the format is based on moment.js

**Comment by iamaamir** [comment]
Yup that seems to be working, thanks
