### ISSUE TITLE
command 'extension.generateAuthorInfo' not found

### ISSUE THREAD

**Issue by icewind7030** [excaliburhan/vscode-author-generator#12]
I got the error like this:
```
command 'extension.generateAuthorInfo' not found
```
Yesterday it still work, maybe caused by recently update?

**Comment by excaliburhan** [comment]
> I got the error like this:
> 
> ```
> command 'extension.generateAuthorInfo' not found
> ```
> 
> Yesterday it still work, maybe caused by recently update?

It's my mistake to ignore node_modules directory causing this error. You can upgrade it to 0.0.10 to fix this.

**Comment by icewind7030** [comment]
Ok, thanks.
