### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by anti-held-333** [excaliburhan/vscode-author-generator#15]
Hello :)
I really love this plug in. Is it possible to generate the Author-Info automatically on new files ?
But more important, is it possible to add a feature, that will run the "update" on saving a file?

Thanks

**Comment by excaliburhan** [comment]
> Hello :)
> I really love this plug in. Is it possible to generate the Author-Info automatically on new files ?
> But more important, is it possible to add a feature, that will run the "update" on saving a file?
> 
> Thanks

update extension and `author-generator.updateOnSave` set `true` to make it updateOnSave

**Comment by anti-held-333** [comment]
thanks! Works perfect!

**Comment by anti-held-333** [comment]
If there is no author info in the file included, the first line will be replaced with the modified date. Is it possible to do a checkup if there exists the content of the template, before inserting the modified date on saving ?

Thanks

**Comment by excaliburhan** [comment]
> If there is no author info in the file included, the first line will be replaced with the modified date. Is it possible to do a checkup if there exists the content of the template, before inserting the modified date on saving ?
> 
> Thanks

version 0.2.1 fixed this. just try new version.

**Comment by anti-held-333** [comment]
Nice Work! Perfect :) 
I still got an idea, is it possible to store templates project specific (for instance by storing them in the project folder under `path-to-project/.vscode` => `path-to-project/.vscode/js.tpl` for a js template). That would help using this plugin with a team, without additional setup.

**Comment by excaliburhan** [comment]
> Nice Work! Perfect :)
> I still got an idea, is it possible to store templates project specific (for instance by storing them in the project folder under `path-to-project/.vscode` => `path-to-project/.vscode/js.tpl` for a js template). That would help using this plugin with a team, without additional setup.

OK, I will close this issue first. If you have any ideas, pr is welcomed.
