### ISSUE TITLE
'_document' of undefined

### ISSUE THREAD

**Issue by parasbansalrs** [excaliburhan/vscode-author-generator#19]
### Environment Details:
```
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
```

### Issue:
Seems like with the latest update of VS Code the extension is not currently working.

![image](https://user-images.githubusercontent.com/53033217/110068986-d3665000-7d9c-11eb-940e-770a7b922d47.png)

### Steps to reproduce:
1. Open command pallet
1. Generate Autor info (use extension)

### Actual 
Getting error
Cannot read property '_document' of undefined

### Expected
The extension should generate the author information

**Comment by parasbansalrs** [comment]
Most likely this issue is from line 19 and 59.
![image](https://user-images.githubusercontent.com/53033217/110069368-a8303080-7d9d-11eb-913a-453fad7464de.png)

**Comment by sushant-kum** [comment]
Any update regarding this? I'm facing the same issue

**Comment by strangeryf** [comment]
Same issue here, after updated to vscode 1.54.1

**Comment by parasbansalrs** [comment]
btw for the time being, I am using a global snippet.
It will not give the auto update on save functionality. But it works for me.
```
  "author-info": {
    "prefix": "author-info",
    "body": [
      "/**",
      " * @author <your_name_here>",
      " * @email <your_email_here>",
      " * @create date ${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE} ${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}",
      " * @modify date ${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE} ${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}",
      " */",
      ""
    ],
    "description": "Generates author information"
  }
```

**Comment by PolarAir** [comment]
same issue here after updating vscode to 1.54.1

**Comment by PolarAir** [comment]
I've made a pull request for this issue which tests and works for me.

Just change the file ~/.vscode/extensions/edwardhjp.vscode-author-generator-0.2.1/generator.js
line 19 and 59
to the following
`let document = editor.document`

**Comment by sushant-kum** [comment]
Just implemented @PolarAir's solution and it seems to be working. Hope the PR is merged into the repo soon and a fix is released.

**Comment by excaliburhan** [comment]
Hey guys. Sorry for my late reply. I've updated a new version V.0.2.2 to adapt to new vscode version. 
Vscode now need to bundle extensions, so I spent sometime to upgrade my old project.
