### ISSUE TITLE
Error of date variable

### ISSUE THREAD

**Issue by LurnD** [excaliburhan/vscode-author-generator#9]
When i generate the author info, the create date and modify date are totally same.
System: macOS 10.14.5
VSCode: Version 1.39.1

**Comment by excaliburhan** [comment]
> When i generate the author info, the create date and modify date are totally same.
> System: macOS 10.14.5
> VSCode: Version 1.39.1

the modify date only changes when you use "Update Author Info".

**Comment by LurnD** [comment]
> > When i generate the author info, the create date and modify date are totally same.
> > System: macOS 10.14.5
> > VSCode: Version 1.39.1
> 
> the modify date only changes when you use "Update Author Info".

Thank you.
